DROP SCHEMA SOLO;
CREATE SCHEMA SOLO;

USE SOLO;

-- 멤버 테이블
DROP TABLE MEMBER;
CREATE TABLE MEMBER (
	`mNo`	INT PRIMARY KEY AUTO_INCREMENT,
	`id`	VARCHAR(30)	NOT NULL UNIQUE,
	`password`	VARCHAR(100)	NOT NULL,
	`role`	VARCHAR(10)	DEFAULT 'ROLE_USER',
	`name`	VARCHAR(15)	NULL,
	`phone`	VARCHAR(13)	NULL,
	`email`	VARCHAR(100)	NULL,
	`address`	VARCHAR(100)	NULL,
	`gender`	VARCHAR(1)	NULL,
	`status`	VARCHAR(1)	DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
	`enrollDate`	DATETIME	 DEFAULT CURRENT_TIMESTAMP,
	`modifyDate`	DATETIME	 DEFAULT CURRENT_TIMESTAMP,
	`birth`	DATETIME	NULL,
	`oriFileNm`	VARCHAR(100)	NULL,
	`reFileNm`	VARCHAR(100)	DEFAULT 'default-avatar.png'
);

SELECT * FROM MEMBER;

-- 회원가입

-- 로그인
SELECT * FROM MEMBER WHERE id = 'admin' AND status = 'Y';